name: Continuous Integration

on: [push, pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: make install

  run_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Python and pytest
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: |
          which python
          python --version
          python -m pytest --version
      - name: Run tests
        run: 
          make install
          make test

  format_code:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run: 
          make install
          make format

  lint_code:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint code
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        run:
          make install 
          make lint
