name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.ipynb'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '**.ipynb'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Pytest
        run: python -m pytest
